### ISSUE TITLE
Microsoft Edge - side scroll

### ISSUE THREAD

**Issue by charlie-quinn** [ccmadrid/portfolio#10]
Your side scroll on the portfolio sections is not working on all screen sizes. I can see the scrollbar, but it does nothing! Just sits there lookin' pretty.

I wish I could be of more help!

@thomasjbradley what do you think?

**Comment by thomasjbradley** [comment]
It's because `.section` has a `margin-top: -1em`, it's being pulled up and covering over of the scroll bars.
https://github.com/ccmadrid/portfolio/blob/gh-pages/css/main.css#L170

**Comment by thatkidmadrid** [comment]
thanks!
