### ISSUE TITLE
Firefox on Nexus 4: loading, centering, and side-scrolling

### ISSUE THREAD

**Issue by kayleemenard** [ccmadrid/portfolio#13]
When I boot up your page, the below screenshot is what it loads as. I have to scroll upwards afterwards to see your menu and banner (also, maybe it's just my eyes, but the text looks slightly off-centered in the blurb):
![2015-10-08 14 59 08](https://cloud.githubusercontent.com/assets/6373202/10370312/3897b736-6dac-11e5-82f1-a2162c9459b3.png)

![2015-10-08 14 59 28](https://cloud.githubusercontent.com/assets/6373202/10370313/39872dac-6dac-11e5-8b86-421564cc587e.png)

**Side-note:**the side scrolling works pretty well, I'm able to flick the photos to scroll or just drag left and right. I don't know how you would go about fixing the scrolling so that the last image sticks to the right side of the viewport so there wouldn't be that odd space or too much extra space:
![2015-10-08 15 05 13](https://cloud.githubusercontent.com/assets/6373202/10370449/e3a1321a-6dac-11e5-9a16-7e7de4a12e85.png) 
![2015-10-08 15 04 47](https://cloud.githubusercontent.com/assets/6373202/10370438/d7ec81ae-6dac-11e5-9399-1e701bfbef55.png)

**Comment by thatkidmadrid** [comment]
thanks for the feedback. Hopefully I can use jekyll to adjust the blank space in the scroll dynamically, but otherwise I'll just have to calculate the correct width for when I have my final pieces in
